name: minecraft_manhunt_latest
version: '1.0-SNAPSHOT'
main: com.hacklab.manhunt.Main
api-version: '1.21'
authors: [ masafumi terazono ]
description: Minecraft Manhunt game plugin

commands:
  manhunt:
    description: Manhunt game commands
    usage: /manhunt <role|start|compass|status|spectate|help>
    aliases: [mh]
  r:
    description: Team chat command for Manhunt
    usage: /r <message>
    aliases: [teamchat]
  pos:
    description: Share your position with teammates
    usage: /pos
    aliases: [position, coords]
  shop:
    description: Open the in-game shop or check balance
    usage: /shop [balance|help]
    aliases: [store]

permissions:
  manhunt.admin:
    description: Administrator permissions for Manhunt
    default: op
  manhunt.use:
    description: Basic usage permissions for Manhunt
    default: true
